=== seyaki/xml-dom4j-Reader-Writer/teachingp/out/production/teachingp/xml110.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT  teachingplan (course+)>
<!ELEMENT course (course-name , class-hour , exam-form)>
<!ATTLIST  course no CDATA "">
<!ELEMENT course-name (#PCDATA)>
<!ELEMENT class-hour (#PCDATA)>
<!ELEMENT exam-form (#PCDATA)>

=== seyaki/xml-dom4j-Reader-Writer/teachingp/src/xml110.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE teachingplan SYSTEM "C:\Users\seyaki\Desktop\teachingplan\src\xml110.dtd">
<!--教学计划-->
 <teachingplan>
 <course no="1">
   <course-name>大学英语</course-name>
   <class-hour>36</class-hour>
   <exam-form>考试</exam-form>
 </course >
 <course no="2">
   <course-name>高等数学</course-name>
   <class-hour>70</class-hour>
   <exam-form>考试</exam-form>
 </course>
 <course no="3">
   <course-name>计算机应用基础</course-name>
   <class-hour>108</class-hour>
   <exam-form>上机考试</exam-form>
 </course>

</teachingplan>
